---
 - hosts: localhost
   connection: local
   gather_facts: no
   vars_files:
    - aws/vars/vpc.yml
    - aws/vars/ec2_key.yml
   tasks:
    - include: aws/tasks/vpc.yml
    - include: aws/tasks/ec2_key.yml

