---
 - name: install python2
   raw: sudo apt-get -y install python-simplejson

 - name: Ensure that the repositories are update
   apt: 
     update_cache: yes

 - name: Upgrade the Server
   apt: 
     upgrade: dist

 - name: Install all the essential packages
   apt:
     name: "{{ ','.join(pkgs_list) }}"
     state: latest
 
 - name: Copy the "10periodic.j2" to the "/etc/apt/apt.conf.d/"
   template: 
     src: 10periodic.j2 
     dest: /etc/apt/apt.conf.d/10periodic 
     owner: root 
     group: root 
     mode: 0644
 
 - name: Copy the "50unattended-upgrades.j2" to the "/etc/apt/apt.conf.d/"
   template: 
     src: 50unattended-upgrades.j2 
     dest: /etc/apt/apt.conf.d/50unattended-upgrades 
     owner: root 
     group: root 
     mode: 0644
 
 - name: Check the Current Timezone
   command: cat /etc/timezone
   register: current_timezone

 - name: Set the provided Timezone
   copy: 
     content: "{{ timezone }}" 
     dest: /etc/timezone 
     owner: root 
     group: root 
     mode: 0644 
     backup: yes
   when: current_timezone.stdout != "{{ timezone }}"
   register: set_timezone

 - name: Update Timezone
   command: dpkg-reconfigure --frontend noninteractive tzdata
   when: set_timezone.changed

