--- # EC2 Instances
- name: Gitlab | Create SSH HTTPS Security Group
  local_action:
    module: ec2_group
    region: "{{ vpc_region }}"
    name: "{{ item.sg_name }}"
    description: "{{ item.sg_description }}"
    state: present
    rules: "{{ item.sg_rules }}"
  with_items: "{{ gitlab_security_groups }}"
  register: gitlab_sg

- name: Basic provisioning of 2 t2.micro EC2 instances)
  local_action:
    module: ec2
    region: "{{ vpc_region }}"
    group: "{{ gitlab_security_groups[0].sg_name }}"
    keypair: "{{ key_name }}"
# Ubuntu image 16.04
    image: ami-60bd2d0c
    instance_type: t2.micro
    count: 2
