---

 - name: RDS | Create RDS Subnet Group
   local_action:
     module: rds_subnet_group
     region: "{{ vpc_region }}"
     state: present
     name: default-vpc-57c9a233
     description: "{{ rds_sg_description }}"
     subnets:
       - subnet-f4b43aac
       - subnet-2c337f48
       - subnet-d2c0baa4
 
 - name: RDS | Provisioning RDS Instance
   local_action:
     module: rds
     command: create
     region: "{{ vpc_region }}"
     multi_zone: "{{ multi_zone_option }}"
     subnet: default-vpc-57c9a233
     vpc_security_groups: sg-2568b743
     instance_name: "{{ rds_instance_name }}"
     db_engine: "{{ rds_db_engine }}"
     size: "{{ rds_db_size }}"
     db_name: "{{ rds_db_name }}"
     instance_type: "{{ rds_instance_type }}"
     username: "{{ rds_db_username }}"
     password: "{{ rds_db_password }}"
     backup_retention: "{{ backup_retention_period }}"
     wait: yes
     wait_timeout: 600
     tags:
       Environment: "{{ ENV }}"
       Application: "{{ application }}"
   register: rds

 - name: RDS | Write the RDS facts/values to the file rds_info.yml inside the project directory
   shell: |
     echo "db_hostname: {{ rds.instance.endpoint }}" > rds_info.yml
     echo "db_name: {{ rds_db_name }}" >> rds_info.yml
     echo "db_username: {{ rds_db_username }}" >> rds_info.yml
     echo "db_password: {{ rds_db_password }}" >> rds_info.yml
